### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by waayaa** [Intelehealth/intelehealth-ui#207]
```
PRODUCTION=false
BASE=XXXXX
BASE_URL=XXXXX
BASE_URL_CORD_APP=XXXXX
BASE_URL_LEGACY=XXXXX
MIND_MAP_URL=XXXXX
NOTIFICATION_URL=XXXXX
SOCKET_URL=XXXXX
CAPTCHA_SITE_KEY=XXXXX
WEB_RTC_SDK_SERVER_URL=XXXXX
WEB_RTC_TOKEN_SERVER_URL=XXXXX
SITE_KEY=XXXXX
EXTERNAL_PRESCRIPTION_CRED=XXXXX
VAPID_PUBLIC_KEY=XXXXX
AUTH_GATE_WAY_URL=XXXXX
FIREBASE_API_KEY=XXXXX
FIREBASE_AUTH_DOMAIN=XXXXX
FIREBASE_PROJECT_ID=XXXXX
FIREBASE_STORAGE_BUCKET=XXXXX
FIREBASE_MESSAGING_SENDER_ID=XXXXX
FIREBASE_APP_ID=XXXXX
SHOW_CAPTCHA=true/false
```
Please can some explain what these keys are for example BASE_URL_CORD_APP
Some are self explanatory some are not.

**Comment by satyadeep-ih** [comment]
These keys are used for setting different environment variables which are used by our product's next version which is slated to be released pretty soon.

**Comment by waayaa** [comment]
What version do you recommend I use for now?

**Comment by satyadeep-ih** [comment]
Continue with master branch for now, we shall keep you posted!

**Comment by sangaleanurag007** [comment]
@waayaa FYI

PRODUCTION=false                                        //Set true for creating a production build and false for development build
BASE=XXXXX                                                   //Base URL of the domain
BASE_URL=XXXXX                                           //Base URL for OpenMRS API endpoints
BASE_URL_CORD_APP=XXXXX                        //Base URL for OpenMRS coreapps to get diagnosis
BASE_URL_LEGACY=XXXXX                             //Base URL for OpenMRS
MIND_MAP_URL=XXXXX                                //Base URL for Mindmap API endpoints
NOTIFICATION_URL=XXXXX                           //Base URL for notification endpoint
SOCKET_URL=XXXXX                                      //Base URL for socket
CAPTCHA_SITE_KEY=XXXXX                           //Re-captcha site public key
WEB_RTC_SDK_SERVER_URL=XXXXX              //Live Kit server base URL
WEB_RTC_TOKEN_SERVER_URL=XXXXX         //Live Kit Token Microservice API endpoint base URL
SITE_KEY=XXXXX                                            //Re-captcha site public key
EXTERNAL_PRESCRIPTION_CRED=XXXXX     //User credentials for external user for e-prescription
VAPID_PUBLIC_KEY=XXXXX                           // VAPID public key for push notification
AUTH_GATE_WAY_URL=XXXXX                     // Base URL for auth gateway proxy server 
FIREBASE_API_KEY=XXXXX                            //Firebase API key
FIREBASE_AUTH_DOMAIN=XXXXX
FIREBASE_PROJECT_ID=XXXXX
FIREBASE_STORAGE_BUCKET=XXXXX
FIREBASE_MESSAGING_SENDER_ID=XXXXX
FIREBASE_APP_ID=XXXXX
SHOW_CAPTCHA=true/false                        //Set true to enable captcha verification for login

**Comment by waayaa** [comment]
EXTERNAL_PRESCRIPTION_CRED=XXXXX //User credentials for external user for e-prescription
AUTH_GATE_WAY_URL=XXXXX // Base URL for auth gateway proxy server

How do these come in to play?

**Comment by satyadeep-ih** [comment]
Auth gateway is an additional layer of security which we are pushing for . That is still private , not in GA yet.
